Repository pelletier/go-toml, pull requests merged in 2021-11, with the labels that each got.

#654 Decoder: use lookup table to validate ASCII
  parser_test.go
  utf8.go
Labels: performance

#656 Decode: correctly handle carriage return in comments
  scanner.go
  unmarshaler_test.go
Labels: bug

#659 Decode: code cleanup for struct cache
  internal/danger/typeid.go
  types.go
  unmarshaler.go
  unmarshaler_test.go
Labels: performance

#660 Decoder: validate inline tables don't redefine keys
  internal/tracker/seen.go
  unmarshaler_test.go
Labels: bug

#661 Update TOML test suite
  toml_testgen_test.go
Labels: build

#663 Decoder: validate inline tables in arrays don't redefine keys
  internal/ast/ast.go
  internal/tracker/seen.go
  unmarshaler_test.go
Labels: bug

#665 Decode: accept E as exponent notation
  parser.go
  unmarshaler_test.go
Labels: bug

#667 Decoder: prevent duplicates of inline tables
  internal/tracker/seen.go
  unmarshaler_test.go
Labels: bug

#670 API: Encoder and Decoder options are chainable
  marshaler.go
  marshaler_test.go
  unmarshaler.go
Labels: feature

#673 Decoder: flag invalid carriage returns in literal strings
  scanner.go
  unmarshaler_test.go
Labels: bug

#680 Decoder: validate bounds of day and month in dates
  decode.go
  unmarshaler_test.go
Labels: bug

#682 Decoder: fix panic on table array behind a pointer
  unmarshaler.go
  unmarshaler_test.go
Labels: bug

#683 Encoder: mention "-" to prevent encoding field in doc
  marshaler.go
Labels: doc

#684 Decoder: show struct field in type mismatch errors
  unmarshaler.go
  unmarshaler_test.go
Labels: feature

#688 Decoder: check timezones start with +,-,z,Z
  decode.go
  parser.go
  unmarshaler_test.go
Labels: bug
