Repository pelletier/go-toml, pull requests merged in 2021-12, with the labels that each got.

#691 Decoder: check tz has : between hours and minutes
  decode.go
  unmarshaler_test.go
Labels: bug

#693 Decoder: allow commas in tags
  unmarshaler.go
  unmarshaler_test.go
Labels: feature

#696 Decode: restrict timezone offset values
  decode.go
  unmarshaler_test.go
Labels: bug

#698 Decode: ensure signed numbers don't start with an underscore
  decode.go
  unmarshaler_test.go
Labels: bug

#699 Decode: ensure signed exponents don't start with an underscore
  decode.go
  unmarshaler_test.go
Labels: bug

#702 Decoder: prevent modification of inline tables
  internal/tracker/seen.go
  unmarshaler_test.go
Labels: bug

#704 Decoder: disallow modification of existing table
  internal/ast/ast.go
  internal/tracker/seen.go
  unmarshaler_test.go
Labels: bug

#706 Decode: fix maximum time offset values
  decode.go
  unmarshaler_test.go
Labels: bug

#709 Decode: allow CRLF as whitespace before line ending backslash
  parser.go
  unmarshaler_test.go
Labels: bug

#711 Encode: add comment struct tag
  marshaler.go
  marshaler_test.go
Labels: feature

#712 Readme: document more differences with v1
  README.md
Labels: doc

#713 Doc: clarify errors returned by Decode
  README.md
  errors_test.go
  unmarshaler.go
Labels: doc

#717 Decode: check buffer length before parsing simple key
  parser.go
  unmarshaler_test.go
Labels: bug

#730 Update and move testsuite to internal package
  cmd/gotoml-test-decoder/main.go
  internal/testsuite/add.go
  internal/testsuite/json.go
  internal/testsuite/parser.go
  internal/testsuite/rm.go
  internal/testsuite/testsuite.go
  toml_testgen_support_test.go
  toml_testgen_test.go
Labels: testing
