Repository pelletier/go-toml, pull requests merged in 2023-08, with the labels that each got.

#885 Add support for `Go 1.21`
  .github/workflows/coverage.yml
  .github/workflows/release.yml
  .github/workflows/workflow.yml
  fuzz_test.go
  ossfuzz/fuzz.go
Labels: go

#884 Build `riscv64` binaries for linux
  .goreleaser.yaml
Labels: build

#887 Decode: fix panic when parsing '0' as a float
  decode.go
  unmarshaler_test.go
Labels: bug

#889 Encode: fix ignored indent of array tables
  marshaler.go
  marshaler_test.go
Labels: bug

#890 unstable/parser: add raw to integers
  unstable/parser.go
  unstable/parser_test.go
Labels: bug

#892 Decode: fix wrong indention for comments on tables
  marshaler.go
  marshaler_test.go
Labels: bug

#893 encoder: add back the commented option
  README.md
  marshaler.go
  marshaler_test.go
Labels: feature
