Repository pelletier/go-toml, pull requests merged in 2023-02, with the labels that each got.

#837 Make inline table children indent better
  marshaler.go
  marshaler_test.go
Labels: bug

#847 Upgrade go 1.20
  .github/workflows/coverage.yml
  .github/workflows/release.yml
  .github/workflows/workflow.yml
  fuzz_test.go
Labels: build

#848 Fix go 1.20 version in github actions
  .github/workflows/coverage.yml
  .github/workflows/release.yml
Labels: build

#841 Allow integers to be unmarshaled into floats
  fast_test.go
  internal/imported_tests/unmarshal_imported_test.go
  unmarshaler.go
Labels: bug

#849 Fix typoes
  README.md
  internal/cli/cli.go
  unmarshaler.go
  unmarshaler_test.go
  unstable/ast.go
  unstable/parser.go
Labels: doc

#853 Fix error reporting of type mismatch on inline tables
  unmarshaler.go
  unmarshaler_test.go
  unstable/parser.go
Labels: bug

#854 Fix panic when unmarshaling into a map twice
  unmarshaler.go
  unmarshaler_test.go
Labels: bug
