Repository pelletier/go-toml, pull requests merged in 2023-05, with the labels that each got.

#863 Support MarshalText/UnmarshalText for map keys
  marshaler.go
  marshaler_test.go
  unmarshaler.go
  unmarshaler_test.go
Labels: feature

#864 fuzz: improve target perf
  ossfuzz/fuzz.go
Labels: build

#867 Add example on how to use TextUnmarshaler
  example_text_marshaling_test.go
  unmarshaler_test.go
Labels: doc

#868 Decode: fix decode into unsettable structs
  unmarshaler.go
  unmarshaler_test.go
Labels: bug

#860 Comments support in unstable/Parser
  unstable/parser.go
  unstable/parser_test.go
  unstable/scanner.go
Labels: feature

#874 Use PtrTo to not require Go 1.18
  unmarshaler.go
Labels: bug

#876 Encode: fix support for arrays
  marshaler.go
  marshaler_test.go
Labels: bug
