Repository pelletier/go-toml, pull requests merged in 2024-08, with the labels that each got.

#958 Allow `int`, `uint`, and `float` as map keys
  marshaler.go
  marshaler_test.go
  unmarshaler.go
  unmarshaler_test.go
Labels: feature

#951 Fix readme typo
  README.md
Labels: doc

#956 Fix reflect.Pointer backward compatibility
  marshaler.go
Labels: bug

#964 Fix goreleaser deprecated attribute name
  .goreleaser.yaml
Labels: build
